name: Python application test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # Match the Python version to what you use in Docker

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install pytest pytest-asyncio httpx

      - name: Run tests
        run: pytest
